"""
Video Tasks — Async background tasks for the full video generation pipeline.
"""
import os
import asyncio
import logging
import shutil
import httpx
from pathlib import Path
from app.config import get_settings
from app.database import async_session
from app.models import VideoProject, VideoScene, VideoRender, VideoStatus

logger = logging.getLogger(__name__)
settings = get_settings()


def _find_custom_background_music(project_id: int) -> str:
    """Return custom uploaded background music path if present."""
    audio_dir = Path(settings.media_dir) / "audio" / str(project_id)
    if not audio_dir.exists():
        return ""
    for ext in (".mp3", ".wav", ".m4a", ".aac", ".ogg", ".flac", ".opus", ".webm"):
        candidate = audio_dir / f"custom_background_music{ext}"
        if candidate.exists():
            return str(candidate)
    return ""


def _find_custom_video(project_id: int) -> str:
    """Return custom uploaded video path if present."""
    vid_dir = Path(settings.media_dir) / "videos" / str(project_id)
    if not vid_dir.exists():
        return ""
    for ext in (".mp4", ".mov", ".avi", ".webm", ".mkv"):
        candidate = vid_dir / f"user_video{ext}"
        if candidate.exists():
            return str(candidate)
    return ""


async def _run_custom_video_pipeline(db, project, project_id: int):
    """Pipeline for user-uploaded video: overlay subtitles + optional narration."""
    from app.services.video_composer import compose_overlay_video
    from app.services.video_composer import _get_duration as get_duration

    video_path = _find_custom_video(project_id)
    if not video_path:
        raise FileNotFoundError("Video do usuario nao encontrado.")

    video_duration = get_duration(video_path)
    if video_duration <= 0:
        video_duration = 60.0
    project.track_duration = round(video_duration)

    narration_path = ""
    has_script = (project.lyrics_text or "").strip()

    # Step 1: Generate TTS narration if user provided a script
    if has_script and project.audio_path and os.path.exists(project.audio_path):
        # Audio already generated by the router
        narration_path = project.audio_path
        logger.info(f"Custom video: using pre-generated narration {narration_path}")
    elif has_script:
        project.status = VideoStatus.GENERATING_SCENES
        project.progress = 10
        await db.commit()
        logger.info(f"Custom video: script provided but no narration audio, subtitles only")

    # Step 2: Transcribe narration or video audio for accurate subtitles
    project.status = VideoStatus.GENERATING_SCENES
    project.progress = 30
    await db.commit()

    transcribed_words = []
    transcribed_text = ""
    # First try: transcribe narration audio if available
    if narration_path and os.path.exists(narration_path):
        try:
            from app.services.transcriber import transcribe_audio
            import asyncio
            lyrics_hint = (project.lyrics_text or "").strip()
            result = await asyncio.get_event_loop().run_in_executor(
                None, lambda: transcribe_audio(narration_path, prompt=lyrics_hint)
            )
            transcribed_words = result.get("words", [])
            transcribed_text = (result.get("text", "") or "").strip()
            if not project.lyrics_text and transcribed_text:
                project.lyrics_text = transcribed_text
                await db.commit()
            logger.info(f"Custom video: narration transcription: {len(transcribed_words)} words")
        except Exception as e:
            logger.warning(f"Custom video: narration transcription failed: {e}")
    # Second: if no narration and no script, transcribe video's own audio for auto-subtitles
    elif not has_script:
        try:
            from app.services.transcriber import transcribe_audio
            import asyncio
            result = await asyncio.get_event_loop().run_in_executor(
                None, lambda: transcribe_audio(video_path)
            )
            transcribed_words = result.get("words", [])
            transcribed_text = (result.get("text", "") or "").strip()
            if transcribed_text:
                project.lyrics_text = transcribed_text
                has_script = True
                await db.commit()
            logger.info(f"Custom video: video audio transcription: {len(transcribed_words)} words, text={len(transcribed_text)} chars")
        except Exception as e:
            logger.warning(f"Custom video: video audio transcription failed: {e}")

    # Step 3: Generate subtitles
    subtitle_path = ""
    enable_subtitles = getattr(project, "enable_subtitles", True)
    if enable_subtitles is None:
        enable_subtitles = True

    if enable_subtitles and (transcribed_words or has_script):
        from app.services.subtitle_generator import generate_ass_subtitles, generate_ass_from_text

        subtitle_dir = Path(settings.media_dir) / "subtitles" / str(project_id)
        subtitle_dir.mkdir(parents=True, exist_ok=True)
        subtitle_path = str(subtitle_dir / "karaoke.ass")

        if transcribed_words:
            generate_ass_subtitles(
                lyrics_words=transcribed_words,
                aspect_ratio=project.aspect_ratio,
                output_path=subtitle_path,
            )
        elif has_script:
            duration = get_duration(narration_path) if narration_path else video_duration
            generate_ass_from_text(
                lyrics_text=project.lyrics_text,
                duration=duration,
                aspect_ratio=project.aspect_ratio,
                output_path=subtitle_path,
            )
        logger.info(f"Custom video: subtitles generated at {subtitle_path}")

    # Step 4: Compose overlay video
    project.status = VideoStatus.RENDERING
    project.progress = 60
    await db.commit()

    import asyncio
    render_result = await asyncio.get_event_loop().run_in_executor(
        None,
        lambda: compose_overlay_video(
            project_id=project_id,
            video_path=video_path,
            subtitle_path=subtitle_path,
            narration_path=narration_path,
            aspect_ratio=project.aspect_ratio,
        ),
    )

    await db.rollback()
    project = await db.get(VideoProject, project_id)

    project.progress = 90
    await db.commit()

    # Step 5: Generate thumbnail (skip if user uploaded custom thumbnail)
    thumb_dir = Path(settings.media_dir) / "thumbnails" / str(project_id)
    thumb_dir.mkdir(parents=True, exist_ok=True)
    thumb_path = str(thumb_dir / "thumbnail.jpg")

    custom_thumb = next(thumb_dir.glob("custom_thumbnail.*"), None)
    if custom_thumb:
        shutil.copy2(str(custom_thumb), thumb_path)
        logger.info(f"Using custom thumbnail for project {project_id}")
    else:
        from app.services.thumbnail_generator import generate_thumbnail_from_frame
        try:
            generate_thumbnail_from_frame(
                video_path=render_result["file_path"],
                title=project.track_title or project.title,
                artist=project.track_artist or "",
                output_path=thumb_path,
            )
        except Exception as e:
            logger.warning(f"Custom video thumbnail failed: {e}")
            thumb_path = ""

    # Save render
    render = VideoRender(
        project_id=project_id,
        format=project.aspect_ratio,
        file_path=render_result["file_path"],
        file_size=render_result["file_size"],
        thumbnail_path=thumb_path,
        duration=render_result["duration"],
    )
    db.add(render)

    project.status = VideoStatus.COMPLETED
    project.progress = 100
    await db.commit()
    logger.info(f"Custom video pipeline complete for project {project_id}")


async def download_audio_if_url(audio_path: str, project_id: int) -> str:
    """If audio_path is a URL, download it locally and return the local path."""
    if not audio_path or not audio_path.startswith(("http://", "https://")):
        return audio_path

    audio_dir = Path(settings.media_dir) / "audio" / str(project_id)
    audio_dir.mkdir(parents=True, exist_ok=True)
    local_path = str(audio_dir / "track.mp3")

    if os.path.exists(local_path):
        return local_path

    logger.info(f"Downloading audio from {audio_path}")
    async with httpx.AsyncClient(timeout=120, follow_redirects=True) as client:
        resp = await client.get(audio_path)
        resp.raise_for_status()
        with open(local_path, "wb") as f:
            f.write(resp.content)

    logger.info(f"Audio downloaded: {local_path} ({os.path.getsize(local_path)} bytes)")
    return local_path


async def run_video_pipeline(project_id: int):
    """Full pipeline: scenes → subtitles → render → thumbnail.
    Runs as a background task.
    """
    async with async_session() as db:
        try:
            project = await db.get(VideoProject, project_id)
            if not project:
                return

            # ── Step 0: Download audio if URL ──
            from app.services.video_composer import compose_video
            from app.services.video_composer import _get_duration as get_audio_duration

            # ── Custom Video Pipeline (user uploaded video → subtitles overlay) ──
            use_custom_video = getattr(project, "use_custom_video", False) or False
            if use_custom_video:
                await _run_custom_video_pipeline(db, project, project_id)
                return

            audio_path = await download_audio_if_url(project.audio_path, project_id) if project.audio_path else ""
            use_custom_images = getattr(project, "use_custom_images", False) or False
            image_display_seconds = float(getattr(project, "image_display_seconds", 0) or 0)
            zoom_images = bool(getattr(project, "zoom_images", True))
            is_music_only_mode = use_custom_images and not (project.lyrics_text or "").strip()

            if (not audio_path or not os.path.exists(audio_path)) and is_music_only_mode:
                # Photo-only mode without uploaded music: generate instrumental soundtrack automatically.
                img_dir = Path(settings.media_dir) / "images" / str(project_id)
                user_images_count = len([p for p in img_dir.glob("user_*") if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}])
                base_seconds = image_display_seconds if image_display_seconds > 0 else 12.0
                target_dur = max(30.0, min(240.0, float(max(user_images_count, 1) * base_seconds)))

                text_hint = f"{project.style_prompt or ''} {project.title or ''}".lower()
                bgm_mood = "inspiracional"
                if any(w in text_hint for w in ["terror", "horror", "misterio", "dark", "suspense"]):
                    bgm_mood = "misterioso"
                elif any(w in text_hint for w in ["urgente", "alerta", "crise", "perigo"]):
                    bgm_mood = "urgente"
                elif any(w in text_hint for w in ["motivac", "superac", "força", "poder"]):
                    bgm_mood = "motivacional"
                elif any(w in text_hint for w in ["reflex", "calma", "paz", "tranquil"]):
                    bgm_mood = "reflexivo"
                elif any(w in text_hint for w in ["drama", "triste", "emocio"]):
                    bgm_mood = "dramatico"

                music_dir = Path(settings.media_dir) / "audio" / str(project_id)
                music_dir.mkdir(parents=True, exist_ok=True)
                main_music_path = str(music_dir / "music_only_main.mp3")

                try:
                    from app.services.suno_music import generate_suno_music

                    topic_hint = project.title or project.style_prompt or ""
                    generated = await generate_suno_music(main_music_path, target_dur, bgm_mood, topic_hint)
                    if generated and os.path.exists(generated):
                        audio_path = generated
                        logger.info(f"Music-only mode: Suno main audio generated for project {project_id}: {generated}")
                except Exception as e:
                    logger.warning(f"Music-only mode: Suno main audio failed for project {project_id}: {e}")

                if not audio_path or not os.path.exists(audio_path):
                    try:
                        from app.services.script_audio import generate_background_music

                        generated = await asyncio.get_event_loop().run_in_executor(
                            None, generate_background_music, main_music_path, target_dur, bgm_mood
                        )
                        if generated and os.path.exists(generated):
                            audio_path = generated
                            logger.info(f"Music-only mode: FFmpeg fallback main audio generated for project {project_id}: {generated}")
                    except Exception as e:
                        logger.warning(f"Music-only mode: FFmpeg fallback main audio failed for project {project_id}: {e}")

                if audio_path and os.path.exists(audio_path):
                    project.audio_path = audio_path
                    real_dur = get_audio_duration(audio_path)
                    project.track_duration = round(real_dur) if real_dur > 0 else round(target_dur)
                    await db.commit()

            if not audio_path or not os.path.exists(audio_path):
                raise FileNotFoundError(f"Audio file not found: {project.audio_path}")

            audio_basename = os.path.basename(audio_path).lower()
            is_music_only_mode = (
                is_music_only_mode
                or audio_basename.startswith("custom_background_music")
                or audio_basename.startswith("music_only_main")
                or "instrumental_no_vocals" in audio_basename
            )

            # ── Step 0b: Transcribe audio with Whisper for accurate karaoke ──
            transcribed_words = []
            if not is_music_only_mode:
                try:
                    from app.services.transcriber import transcribe_audio
                    lyrics_hint = (project.lyrics_text or "").strip()
                    result = await asyncio.get_event_loop().run_in_executor(
                        None, lambda: transcribe_audio(audio_path, prompt=lyrics_hint)
                    )
                    transcribed_words = result.get("words", [])
                    # Use transcribed text if we had no lyrics
                    if not project.lyrics_text and result.get("text"):
                        project.lyrics_text = result["text"]
                        await db.commit()
                    logger.info(f"Whisper transcription: {len(transcribed_words)} words")
                except Exception as e:
                    logger.warning(f"Whisper transcription failed, will use text fallback: {e}")
            else:
                logger.info(f"Music-only mode for project {project_id}: skipping Whisper transcription")

            # ── Early: Start Suno background music generation (runs in parallel with scenes) ──
            suno_music_task = None
            bgm_mood = "inspiracional"
            no_bgm = getattr(project, 'no_background_music', False) or False
            custom_bgm_path = "" if no_bgm else _find_custom_background_music(project_id)
            if no_bgm:
                logger.info(f"Background music DISABLED for project {project_id}")
            elif custom_bgm_path:
                logger.info(f"Using custom uploaded background music for project {project_id}: {custom_bgm_path}")
            if not no_bgm and not custom_bgm_path and audio_path and os.path.basename(audio_path) == "narration.mp3":
                try:
                    from app.services.suno_music import generate_suno_music
                    from app.services.video_composer import _get_duration as get_audio_duration

                    music_dir = Path(settings.media_dir) / "audio" / str(project_id)
                    music_dir.mkdir(parents=True, exist_ok=True)
                    music_path = str(music_dir / "background_music.mp3")

                    audio_dur = get_audio_duration(audio_path)
                    if audio_dur > 0:
                        # Detect mood from project data
                        text_hint = f"{project.style_prompt or ''} {project.title or ''}".lower()
                        if any(w in text_hint for w in ["terror", "horror", "misterio", "dark", "suspense"]):
                            bgm_mood = "misterioso"
                        elif any(w in text_hint for w in ["urgente", "alerta", "crise", "perigo"]):
                            bgm_mood = "urgente"
                        elif any(w in text_hint for w in ["motivac", "superac", "força", "poder"]):
                            bgm_mood = "motivacional"
                        elif any(w in text_hint for w in ["reflex", "calma", "paz", "tranquil"]):
                            bgm_mood = "reflexivo"
                        elif any(w in text_hint for w in ["drama", "triste", "emocio"]):
                            bgm_mood = "dramatico"

                        topic_hint = project.title or project.style_prompt or ""
                        suno_music_task = asyncio.create_task(
                            generate_suno_music(music_path, audio_dur, bgm_mood, topic_hint)
                        )
                        logger.info(f"Suno music generation started in background (mood={bgm_mood})")
                except Exception as e:
                    logger.warning(f"Failed to start Suno music task: {e}")

            # ── Step 1: Generate scenes (images) ──
            project.status = VideoStatus.GENERATING_SCENES
            project.progress = 5
            await db.commit()

            style_prompt = project.style_prompt or ""
            is_black_screen = "tela_preta" in style_prompt.lower()
            is_karaoke = getattr(project, "is_karaoke", False) or False

            # Map style tags to rich English descriptions for better image generation
            _STYLE_DESCRIPTIONS = {
                "cinematic": "cinematic, dramatic lighting, movie-like atmosphere, depth of field",
                "minimalista": "minimalist, clean, simple geometric shapes, subtle colors, elegant",
                "colorido": "colorful, vibrant, bright saturated colors, dynamic composition",
                "dark": "dark, moody, deep shadows, mysterious atmosphere, dramatic contrast",
                "neon": "neon lights, glowing colors, cyberpunk aesthetic, electric atmosphere",
                "vintage": "vintage, retro, film grain, warm nostalgic tones, 1970s",
                "futurista": "futuristic, sci-fi, high-tech, sleek modern design, holographic",
                "natureza": "beautiful nature landscape, lush green forest, mountains, rivers, flowers, golden sunlight, scenic",
                "urbano": "urban cityscape, city skyline at night, street lights, metropolitan architecture",
                "editorial": "editorial, fashion, high contrast, stylish composition, magazine quality",
                "anime": "anime style, Japanese animation, vibrant cel-shaded, detailed illustration",
                "aquarela": "watercolor painting, soft brushstrokes, artistic, pastel colors, dreamy",
                "desenho": "colorful hand-drawn illustration, vibrant sketch art, detailed pencil and watercolor drawing, rich saturated colors, artistic brushstrokes, illustrated storybook style, cartoon illustration with vivid palette",
            }

            def _expand_style_prompt(raw: str) -> str:
                """Expand style tags into rich English descriptions."""
                if not raw:
                    return "cinematic, vibrant colors, dynamic lighting"
                parts = [t.strip().lower() for t in raw.split(",")]
                expanded = []
                for p in parts:
                    expanded.append(_STYLE_DESCRIPTIONS.get(p, p))
                return ", ".join(expanded) if expanded else raw

            if is_karaoke and not use_custom_images:
                # Karaoke mode: generate a single background image for the entire video
                from app.services.scene_generator import generate_scene_image
                img_dir = Path(settings.media_dir) / "images" / str(project_id)
                img_dir.mkdir(parents=True, exist_ok=True)
                output_path = str(img_dir / "scene_000.png")

                visual_prompt = _expand_style_prompt(style_prompt)
                karaoke_prompt = f"{visual_prompt}. Abstract musical background, no text, no people, atmospheric, suitable for karaoke lyrics overlay"

                if is_black_screen:
                    from PIL import Image
                    ar = project.aspect_ratio or "16:9"
                    bw, bh = (1080, 1920) if ar == "9:16" else (1080, 1080) if ar == "1:1" else (1920, 1080)
                    Image.new("RGB", (bw, bh), (0, 0, 0)).save(output_path)
                else:
                    try:
                        loop = asyncio.get_event_loop()
                        await loop.run_in_executor(
                            None, generate_scene_image, karaoke_prompt,
                            project.aspect_ratio or "16:9", output_path,
                        )
                    except Exception as e:
                        logger.warning(f"Karaoke image generation failed, using black screen: {e}")
                        from PIL import Image
                        ar = project.aspect_ratio or "16:9"
                        bw, bh = (1080, 1920) if ar == "9:16" else (1080, 1080) if ar == "1:1" else (1920, 1080)
                        Image.new("RGB", (bw, bh), (0, 0, 0)).save(output_path)

                dur = project.track_duration or 180
                scenes = [{
                    "scene_index": 0,
                    "start_time": 0,
                    "end_time": dur,
                    "visual_prompt": karaoke_prompt,
                    "image_path": output_path,
                    "lyrics_segment": "",
                    "is_chorus": False,
                }]
                project.progress = 40
                await db.commit()
                logger.info(f"Karaoke mode: single background image for {dur:.0f}s")

            elif use_custom_images:
                # User uploaded their own photos — use them directly, skip AI generation
                img_dir = Path(settings.media_dir) / "images" / str(project_id)
                user_images = sorted(
                    [str(p) for p in img_dir.glob("user_*") if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}]
                )
                if not user_images:
                    raise RuntimeError("Nenhuma foto encontrada. Envie pelo menos uma foto.")

                dur = project.track_duration or 180
                # Distribute images evenly across audio duration, cycling if needed
                if image_display_seconds > 0:
                    per_image = max(image_display_seconds, 1.0)
                    desired_dur = per_image * len(user_images)
                    # Trim audio to match user's desired total duration
                    if dur > desired_dur + 2.0:
                        trimmed_path = str(Path(audio_path).parent / "trimmed_audio.mp3")
                        try:
                            import subprocess
                            trim_cmd = [
                                "ffmpeg", "-y", "-i", audio_path,
                                "-t", f"{desired_dur:.2f}",
                                "-af", f"afade=t=out:st={max(desired_dur - 3, 0):.2f}:d=3",
                                "-c:a", "libmp3lame", "-b:a", "192k", trimmed_path,
                            ]
                            subprocess.run(trim_cmd, capture_output=True, text=True, timeout=120)
                            if os.path.exists(trimmed_path) and os.path.getsize(trimmed_path) > 0:
                                audio_path = trimmed_path
                                project.audio_path = audio_path
                                project.track_duration = round(desired_dur)
                                await db.commit()
                                logger.info(f"Audio trimmed to {desired_dur:.1f}s to match user image_display_seconds")
                        except Exception as e:
                            logger.warning(f"Audio trim failed, using original: {e}")
                    dur = desired_dur
                else:
                    per_image = max(dur / len(user_images), 5.0) if len(user_images) <= 20 else 5.0
                scenes = []
                t = 0.0
                idx = 0
                while t < dur:
                    image_path = user_images[idx % len(user_images)]
                    end_t = min(t + per_image, dur)
                    if dur - end_t < 2.0:
                        end_t = dur
                    scenes.append({
                        "scene_index": len(scenes),
                        "start_time": t,
                        "end_time": end_t,
                        "visual_prompt": "user uploaded photo",
                        "image_path": image_path,
                        "lyrics_segment": "",
                        "is_chorus": False,
                        "is_user_uploaded": True,
                    })
                    t = end_t
                    idx += 1
                project.progress = 40
                await db.commit()
                logger.info(f"Custom images mode: {len(user_images)} photos, {len(scenes)} scene slots, {dur:.0f}s total")

            elif is_black_screen:
                # Black screen mode — no image generation, create a single black frame
                from PIL import Image
                if project.aspect_ratio == "9:16":
                    bw, bh = 1080, 1920
                elif project.aspect_ratio == "1:1":
                    bw, bh = 1080, 1080
                else:
                    bw, bh = 1920, 1080
                black_dir = Path(settings.media_dir) / "images" / str(project_id)
                black_dir.mkdir(parents=True, exist_ok=True)
                black_path = str(black_dir / "black.png")
                Image.new("RGB", (bw, bh), (0, 0, 0)).save(black_path)
                dur = project.track_duration or 180
                scenes = [{"scene_index": 0, "start_time": 0, "end_time": dur,
                           "visual_prompt": "black screen", "image_path": black_path,
                           "lyrics_segment": "", "is_chorus": False}]
                project.progress = 40
                await db.commit()
                logger.info(f"Black screen mode: single black frame for {dur:.0f}s")
            else:
                from app.services.scene_generator import generate_all_scenes

                async def _scene_progress(done, total):
                    # Map scene progress to 5-40% range
                    pct = 5 + int((done / total) * 35)
                    project.progress = min(pct, 40)
                    await db.commit()

                scenes = await generate_all_scenes(
                    project_id=project_id,
                    lyrics_text=project.lyrics_text or "",
                    lyrics_words=project.lyrics_words or [],
                    duration=project.track_duration or 180,
                    aspect_ratio=project.aspect_ratio,
                    style_hint=_expand_style_prompt(style_prompt),
                    user_id=project.user_id,
                    on_progress=_scene_progress,
                )

            # Save scenes to DB
            for s in scenes:
                scene = VideoScene(
                    project_id=project_id,
                    scene_index=s.get("scene_index", 0),
                    scene_type="image",
                    prompt=s.get("visual_prompt", ""),
                    image_path=s.get("image_path"),
                    start_time=s.get("start_time", 0),
                    end_time=s.get("end_time", 0),
                    lyrics_segment=s.get("lyrics_segment", ""),
                    is_user_uploaded=s.get("is_user_uploaded", False),
                )
                db.add(scene)

            project.progress = 40
            await db.commit()

            project.progress = 60
            await db.commit()

            # ── Step 2: Generate karaoke subtitles (skip for tela_preta or disabled) ──
            subtitle_path = ""
            enable_subtitles = getattr(project, "enable_subtitles", True)
            if enable_subtitles is None:
                enable_subtitles = True
            if not is_black_screen and enable_subtitles:
                from app.services.subtitle_generator import generate_ass_subtitles, generate_ass_from_text

                subtitle_dir = Path(settings.media_dir) / "subtitles" / str(project_id)
                subtitle_dir.mkdir(parents=True, exist_ok=True)
                subtitle_path = str(subtitle_dir / "karaoke.ass")

                if transcribed_words:
                    # Best: Whisper word-level timestamps → accurate karaoke
                    generate_ass_subtitles(
                        lyrics_words=transcribed_words,
                        aspect_ratio=project.aspect_ratio,
                        output_path=subtitle_path,
                    )
                elif project.lyrics_words:
                    generate_ass_subtitles(
                        lyrics_words=project.lyrics_words,
                        aspect_ratio=project.aspect_ratio,
                        output_path=subtitle_path,
                    )
                elif project.lyrics_text:
                    generate_ass_from_text(
                        lyrics_text=project.lyrics_text,
                        duration=project.track_duration or 180,
                        aspect_ratio=project.aspect_ratio,
                        output_path=subtitle_path,
                    )
                else:
                    subtitle_path = ""
            else:
                logger.info(f"Skipping subtitle generation (tela_preta={is_black_screen}, enable_subtitles={enable_subtitles})")

            project.progress = 70
            await db.commit()

            # ── Step 3: Get background music (Suno task started earlier) ──
            background_music_path = "" if is_music_only_mode else (custom_bgm_path or "")
            if suno_music_task is not None:
                try:
                    background_music_path = await suno_music_task
                    logger.info(f"Suno background music result: {background_music_path}")
                except Exception as e:
                    logger.warning(f"Suno music await failed: {e}")

            # Fallback to FFmpeg synthesis if Suno didn't produce music
            if not no_bgm and not custom_bgm_path and not background_music_path and audio_path and os.path.basename(audio_path) == "narration.mp3":
                try:
                    from app.services.script_audio import generate_background_music
                    from app.services.video_composer import _get_duration as get_audio_duration

                    music_dir = Path(settings.media_dir) / "audio" / str(project_id)
                    music_dir.mkdir(parents=True, exist_ok=True)
                    music_path = str(music_dir / "background_music.mp3")

                    audio_dur = get_audio_duration(audio_path)
                    if audio_dur > 0:
                        background_music_path = await asyncio.get_event_loop().run_in_executor(
                            None, generate_background_music, music_path, audio_dur, bgm_mood
                        )
                        logger.info(f"FFmpeg fallback music ready: {background_music_path}")
                except Exception as e:
                    logger.warning(f"FFmpeg fallback music also failed: {e}")

            # ── Step 4: Compose video with FFmpeg ──
            project.status = VideoStatus.RENDERING
            project.progress = 75
            await db.commit()

            if not audio_path or not os.path.exists(audio_path):
                raise FileNotFoundError(f"Audio file not found: {project.audio_path}")

            # Run FFmpeg in thread pool to avoid blocking event loop and DB timeout
            render_result = await asyncio.get_event_loop().run_in_executor(
                None,
                lambda: compose_video(
                    project_id=project_id,
                    scenes=scenes,
                    audio_path=audio_path,
                    subtitle_path=subtitle_path,
                    aspect_ratio=project.aspect_ratio,
                    background_music_path=background_music_path,
                    enable_zoom=zoom_images,
                ),
            )

            # Refresh DB session after long render to avoid stale connections
            await db.rollback()
            project = await db.get(VideoProject, project_id)

            project.progress = 90
            await db.commit()

            # ── Step 5: Generate thumbnail (skip if user uploaded custom) ──
            thumb_dir = Path(settings.media_dir) / "thumbnails" / str(project_id)
            thumb_dir.mkdir(parents=True, exist_ok=True)
            thumb_path = str(thumb_dir / "thumbnail.jpg")

            custom_thumb = next(thumb_dir.glob("custom_thumbnail.*"), None)
            if custom_thumb:
                shutil.copy2(str(custom_thumb), thumb_path)
                logger.info(f"Using custom thumbnail for project {project_id}")
            else:
                from app.services.thumbnail_generator import generate_thumbnail
                try:
                    generate_thumbnail(
                        title=project.track_title or project.title,
                        artist=project.track_artist or "",
                        output_path=thumb_path,
                    )
                except Exception as e:
                    logger.warning(f"Thumbnail generation failed, using frame fallback: {e}")
                    from app.services.thumbnail_generator import generate_thumbnail_from_frame
                    generate_thumbnail_from_frame(
                        video_path=render_result["file_path"],
                        title=project.track_title or project.title,
                        artist=project.track_artist or "",
                        output_path=thumb_path,
                    )

            # ── Save render to DB ──
            render = VideoRender(
                project_id=project_id,
                format=project.aspect_ratio,
                file_path=render_result["file_path"],
                file_size=render_result["file_size"],
                thumbnail_path=thumb_path,
                duration=render_result["duration"],
            )
            db.add(render)

            project.status = VideoStatus.COMPLETED
            project.progress = 100
            await db.commit()

            logger.info(f"Video pipeline complete for project {project_id}")

        except Exception as e:
            logger.error(f"Video pipeline failed for project {project_id}: {e}", exc_info=True)
            project = await db.get(VideoProject, project_id)
            if project:
                project.status = VideoStatus.FAILED
                project.error_message = str(e)[:1000]
                await db.commit()


async def run_video_format_copy_pipeline(project_id: int, source_video_path: str):
    """Create a new project render by reformatting an existing rendered video."""
    async with async_session() as db:
        project = None
        try:
            project = await db.get(VideoProject, project_id)
            if not project:
                return

            project.status = VideoStatus.RENDERING
            project.progress = 20
            project.error_message = None
            await db.commit()

            from app.services.video_composer import reformat_video

            render_result = await asyncio.get_event_loop().run_in_executor(
                None,
                lambda: reformat_video(
                    project_id=project_id,
                    source_video_path=source_video_path,
                    aspect_ratio=project.aspect_ratio,
                ),
            )

            await db.rollback()
            project = await db.get(VideoProject, project_id)
            if not project:
                return

            project.progress = 90
            await db.commit()

            from app.services.thumbnail_generator import generate_thumbnail_from_frame

            thumb_dir = Path(settings.media_dir) / "thumbnails" / str(project_id)
            thumb_dir.mkdir(parents=True, exist_ok=True)
            thumb_path = str(thumb_dir / "thumbnail.jpg")

            generate_thumbnail_from_frame(
                video_path=render_result["file_path"],
                title=project.track_title or project.title,
                artist=project.track_artist or "",
                output_path=thumb_path,
            )

            render = VideoRender(
                project_id=project_id,
                format=project.aspect_ratio,
                file_path=render_result["file_path"],
                file_size=render_result["file_size"],
                thumbnail_path=thumb_path,
                duration=render_result["duration"],
            )
            db.add(render)

            project.status = VideoStatus.COMPLETED
            project.progress = 100
            await db.commit()

            logger.info(f"Format-copy pipeline complete for project {project_id}")

        except Exception as e:
            logger.error(f"Format-copy pipeline failed for project {project_id}: {e}", exc_info=True)
            if project is None:
                project = await db.get(VideoProject, project_id)
            if project:
                project.status = VideoStatus.FAILED
                project.error_message = str(e)[:1000]
                await db.commit()


async def _combine_realistic_audio(
    video_path: str,
    narration_path: str,
    music_path: str,
    output_path: str,
    video_duration: float,
):
    """Combine narration and/or background music with a silent video using FFmpeg."""
    import subprocess

    inputs = ["-i", video_path]
    filter_parts = []
    audio_index = 1

    if narration_path and os.path.exists(narration_path):
        inputs.extend(["-i", narration_path])
        filter_parts.append(f"[{audio_index}:a]aresample=44100,volume=1.0[narr]")
        audio_index += 1

    if music_path and os.path.exists(music_path):
        inputs.extend(["-stream_loop", "-1", "-i", music_path])
        # Music volume: lower if narration is present
        music_vol = "0.15" if narration_path and os.path.exists(narration_path) else "0.5"
        fade_start = max(0, video_duration - 3)
        filter_parts.append(
            f"[{audio_index}:a]aresample=44100,volume={music_vol},"
            f"afade=t=out:st={fade_start}:d=3[music]"
        )
        audio_index += 1

    if not filter_parts:
        return  # Nothing to combine

    # Build the amix filter
    has_narr = narration_path and os.path.exists(narration_path)
    has_music = music_path and os.path.exists(music_path)

    if has_narr and has_music:
        filter_complex = ";".join(filter_parts) + ";[narr][music]amix=inputs=2:duration=first:normalize=0[aout]"
    elif has_narr:
        filter_complex = filter_parts[0].replace("[narr]", "[aout]")
    else:
        filter_complex = filter_parts[0].replace("[music]", "[aout]")

    cmd = [
        "ffmpeg", "-y",
        *inputs,
        "-filter_complex", filter_complex,
        "-map", "0:v:0",
        "-map", "[aout]",
        "-c:v", "copy",
        "-c:a", "aac", "-b:a", "192k",
        "-t", str(video_duration),
        "-shortest",
        output_path,
    ]

    logger.info(f"Combining audio with video: {' '.join(cmd[:10])}...")
    proc = await asyncio.get_event_loop().run_in_executor(
        None,
        lambda: subprocess.run(cmd, capture_output=True, text=True, timeout=120),
    )
    if proc.returncode != 0:
        logger.error(f"FFmpeg combine failed: {proc.stderr[:500]}")
        raise RuntimeError(f"FFmpeg audio merge failed: {proc.stderr[:200]}")


async def run_realistic_video_pipeline(project_id: int):
    """Pipeline for realistic video generation via Seedance 2.0 or MiniMax Hailuo.
    Much simpler than the standard pipeline: optimize prompt → generate → thumbnail → done.
    """
    async with async_session() as db:
        try:
            project = await db.get(VideoProject, project_id)
            if not project:
                return

            from app.services.seedance_video import optimize_prompt_for_seedance, generate_realistic_video, sanitize_prompt_for_retry
            from app.services.video_composer import _get_duration as get_duration

            # Determine engine from audio_path field (used to store engine choice)
            engine = (project.audio_path or "").strip()
            if engine not in ("seedance", "minimax", "wan2", "grok"):
                engine = "seedance"
            engine_labels = {"minimax": "MiniMax Hailuo", "wan2": "Wan 2.2", "seedance": "Seedance 2.0", "grok": "Grok"}
            engine_label = engine_labels.get(engine, "Seedance 2.0")
            logger.info(f"Realistic video pipeline for project {project_id} using engine: {engine}")

            # ── Step 1: Optimize prompt via GPT ──
            project.status = VideoStatus.GENERATING_SCENES
            project.progress = 5
            await db.commit()

            user_prompt = (project.lyrics_text or "").strip()
            if not user_prompt:
                raise ValueError("Nenhuma descricao fornecida para o video realista.")

            # Check for reference image (stored in style_prompt as file path)
            image_path = None
            if project.style_prompt and os.path.exists(project.style_prompt):
                image_path = project.style_prompt
                logger.info(f"Realistic video with reference image: {image_path}")

            duration = int(project.track_duration or 7)
            max_dur = 15 if engine == "grok" else 10
            duration = max(1, min(duration, max_dur))

            if engine == "grok":
                from app.services.grok_video import optimize_prompt_for_grok
                optimized_prompt = await optimize_prompt_for_grok(
                    user_description=user_prompt,
                    duration=duration,
                )
            else:
                optimized_prompt = await optimize_prompt_for_seedance(
                    user_description=user_prompt,
                    duration=duration,
                )
            logger.info(f"Realistic video prompt optimized for project {project_id}: {optimized_prompt[:200]}...")

            project.progress = 10
            await db.commit()

            # ── Step 2: Generate video ──
            project.status = VideoStatus.RENDERING
            project.progress = 15
            await db.commit()

            render_dir = Path(settings.media_dir) / "renders" / str(project_id)
            render_dir.mkdir(parents=True, exist_ok=True)
            output_path = str(render_dir / "realistic_video.mp4")

            aspect_ratio = project.aspect_ratio or "16:9"
            generate_audio = not getattr(project, "no_background_music", False)

            async def _on_progress(pct, msg):
                nonlocal project
                try:
                    project.progress = pct
                    await db.commit()
                except Exception:
                    pass

            if engine == "grok":
                # ── Grok (image-to-video): generate image first, then video ──
                from app.services.grok_video import generate_video_clip
                from app.services.scene_generator import generate_scene_image

                await _on_progress(16, "Gerando imagem de referencia...")
                grok_image_path = image_path
                if not grok_image_path:
                    # Generate reference image via Nano Banana
                    img_dir = render_dir / "grok_ref"
                    img_dir.mkdir(parents=True, exist_ok=True)
                    grok_image_path = str(img_dir / "reference.png")
                    # Use a concise visual prompt for image generation
                    img_prompt = optimized_prompt[:500]
                    loop = asyncio.get_event_loop()
                    await loop.run_in_executor(
                        None, generate_scene_image, img_prompt, aspect_ratio, grok_image_path
                    )
                    logger.info(f"Grok reference image generated: {grok_image_path}")

                await _on_progress(18, "Iniciando geracao de video Grok...")
                await generate_video_clip(
                    image_path=grok_image_path,
                    prompt=optimized_prompt,
                    output_path=output_path,
                    duration=duration,
                    aspect_ratio=aspect_ratio,
                    on_progress=_on_progress,
                )
            elif engine == "minimax":
                # ── MiniMax Hailuo ──
                from app.services.minimax_video import generate_minimax_video
                await generate_minimax_video(
                    prompt=optimized_prompt,
                    duration=duration,
                    aspect_ratio=aspect_ratio,
                    output_path=output_path,
                    image_path=image_path,
                    on_progress=_on_progress,
                )
            elif engine == "wan2":
                # ── Wan 2.2 via RunPod ──
                from app.services.runpod_video import generate_wan_video
                await generate_wan_video(
                    prompt=optimized_prompt,
                    duration=duration,
                    aspect_ratio=aspect_ratio,
                    output_path=output_path,
                    image_path=image_path,
                    on_progress=_on_progress,
                )
            else:
                # ── Seedance 2.0 (with auto-retry on content filter) ──
                final_prompt = optimized_prompt
                max_retries = 2
                for attempt in range(max_retries + 1):
                    try:
                        await generate_realistic_video(
                            prompt=final_prompt,
                            duration=duration,
                            aspect_ratio=aspect_ratio,
                            output_path=output_path,
                            generate_audio=generate_audio,
                            image_path=image_path,
                            on_progress=_on_progress,
                        )
                        break  # Success
                    except RuntimeError as e:
                        error_msg = str(e)
                        if ("flagged as sensitive" in error_msg or "E005" in error_msg) and attempt < max_retries:
                            logger.warning(f"Seedance content filter triggered (attempt {attempt+1}/{max_retries+1}), sanitizing prompt...")
                            project.progress = 10
                            await db.commit()
                            final_prompt = await sanitize_prompt_for_retry(final_prompt)
                            logger.info(f"Retrying with sanitized prompt: {final_prompt[:200]}...")
                            project.progress = 15
                            await db.commit()
                        else:
                            raise

            await db.rollback()
            project = await db.get(VideoProject, project_id)

            if not os.path.exists(output_path) or os.path.getsize(output_path) == 0:
                raise RuntimeError(f"{engine_label} nao gerou o video ou o arquivo esta vazio.")

            file_size = os.path.getsize(output_path)
            video_duration = get_duration(output_path) if os.path.exists(output_path) else float(duration)
            if video_duration <= 0:
                video_duration = float(duration)

            project.progress = 80
            await db.commit()

            # ── Step 3: Generate audio (narration + music) for engines without native audio ──
            tags = project.tags if isinstance(project.tags, dict) else {}
            add_music = tags.get("add_music", False)
            add_narration = tags.get("add_narration", False)
            narration_voice = tags.get("narration_voice", "onyx")
            narration_text = (project.description or "").strip() if add_narration else ""

            final_video_path = output_path
            has_audio = False

            if engine in ("minimax", "wan2", "grok") and (add_narration or add_music):
                audio_dir = Path(settings.media_dir) / "audio" / str(project_id)
                audio_dir.mkdir(parents=True, exist_ok=True)

                narration_path = ""
                music_path = ""

                # Generate narration via TTS
                if add_narration and narration_text:
                    project.progress = 82
                    await db.commit()
                    logger.info(f"Generating narration for realistic video {project_id}: voice={narration_voice}")
                    try:
                        from app.services.script_audio import generate_tts_audio
                        narration_path = await generate_tts_audio(
                            text=narration_text,
                            voice=narration_voice,
                            project_id=project_id,
                            voice_type="builtin",
                            pause_level="normal",
                            tone="informativo",
                        )
                        logger.info(f"Narration generated: {narration_path}")
                    except Exception as e:
                        logger.warning(f"Narration generation failed: {e}")
                        narration_path = ""

                # Generate background music via Tevoxi
                if add_music:
                    project.progress = 85
                    await db.commit()
                    logger.info(f"Generating background music for realistic video {project_id}")
                    try:
                        from app.services.tevoxi_music import generate_music_from_theme
                        music_theme = user_prompt[:200]
                        music_result = await generate_music_from_theme(
                            theme=music_theme,
                            project_id=project_id,
                            duration=max(int(video_duration) + 5, 30),
                            manual_settings={
                                "music_mode": "instrumental",
                                "music_duration": max(int(video_duration) + 5, 30),
                            },
                        )
                        music_path = music_result.get("audio_path", "")
                        logger.info(f"Background music generated: {music_path}")
                    except Exception as e:
                        logger.warning(f"Music generation failed, trying FFmpeg fallback: {e}")
                        try:
                            from app.services.script_audio import generate_background_music
                            music_path = str(audio_dir / "bgm_fallback.mp3")
                            generate_background_music(music_path, video_duration + 2)
                        except Exception as e2:
                            logger.warning(f"FFmpeg music fallback also failed: {e2}")
                            music_path = ""

                # Combine audio tracks with video using FFmpeg
                project.progress = 88
                await db.commit()

                if narration_path or music_path:
                    combined_path = str(render_dir / "realistic_video_final.mp4")
                    try:
                        await _combine_realistic_audio(
                            video_path=output_path,
                            narration_path=narration_path,
                            music_path=music_path,
                            output_path=combined_path,
                            video_duration=video_duration,
                        )
                        if os.path.exists(combined_path) and os.path.getsize(combined_path) > 0:
                            final_video_path = combined_path
                            file_size = os.path.getsize(combined_path)
                            has_audio = True
                            logger.info(f"Audio combined into video: {combined_path}")
                        else:
                            logger.warning("Combined video is empty, using original")
                    except Exception as e:
                        logger.warning(f"Audio combination failed, using video without audio: {e}")

            project.progress = 90
            await db.commit()

            # ── Step 4: Generate thumbnail from video frame ──
            thumb_dir = Path(settings.media_dir) / "thumbnails" / str(project_id)
            thumb_dir.mkdir(parents=True, exist_ok=True)
            thumb_path = str(thumb_dir / "thumbnail.jpg")

            from app.services.thumbnail_generator import generate_thumbnail_from_frame
            try:
                generate_thumbnail_from_frame(
                    video_path=final_video_path,
                    title=project.title or "Video Realista",
                    artist=engine_label,
                    output_path=thumb_path,
                )
            except Exception as e:
                logger.warning(f"Realistic video thumbnail failed: {e}")
                thumb_path = ""

            project.progress = 95
            await db.commit()

            # ── Step 5: Save render to DB ──
            render = VideoRender(
                project_id=project_id,
                format=aspect_ratio,
                file_path=final_video_path,
                file_size=file_size,
                thumbnail_path=thumb_path,
                duration=video_duration,
            )
            db.add(render)

            project.status = VideoStatus.COMPLETED
            project.progress = 100
            project.track_duration = video_duration
            await db.commit()

            logger.info(f"Realistic video pipeline complete for project {project_id} ({video_duration:.1f}s)")

        except Exception as e:
            logger.error(f"Realistic video pipeline failed for project {project_id}: {e}", exc_info=True)
            project = await db.get(VideoProject, project_id)
            if project:
                project.status = VideoStatus.FAILED
                project.error_message = str(e)[:1000]
                await db.commit()
